# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20171111_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='whether_approved',
            field=models.CharField(choices=[('unknown', 'unknown'), ('yes', 'approved'), ('no', 'no')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentjob',
            name='status',
            field=models.CharField(choices=[('applied', 'applied'), ('approved', 'approved'), ('disapproved', 'disapproved'), ('finished', 'finished')], default='applied', max_length=20),
        ),
    ]
